Models/Account.cs
namespace Task2.Models
{
    public class Account
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

Models/Course.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Task2.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Degree { get; set; }
        public int minDegree { get; set; }
        [ForeignKey("Department")]
        public int Dept_id { get; set; }
    }
}

Models/CrsResult.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Task2.Models
{
    public class CrsResult
    {
        public int Id { get; set; }
        public int Degree { get; set; }
        [ForeignKey("Course")]
        public int Crs_id { get; set; }
        [ForeignKey("Trainee")]
        public int Trainee_id { get; set; }
    }
}

Models/Department.cs
namespace Task2.Models
{
    public class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Manager { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Task2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ITIEntities.cs
using Microsoft.EntityFrameworkCore;

namespace Task2.Models
{
    public class ITIEntities :DbContext
    {
        public ITIEntities() : base()
        {
        }

        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Trainee> Trainees { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CrsResult> CrsResults { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Task2DB ;Integrated Security=True");
        }
    }
}

Models/Instructor.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Task2.Models
{
    public class Instructor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Salary {  get; set; }
        public string Address { get; set; }
        [ForeignKey("Department")]
        public int Dept_id { get; set; }
        [ForeignKey("Course")]
        public int Crs_id { get; set; }
    }
}

Models/Trainee.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Task2.Models
{
    public class Trainee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public int Grade { get; set; }
        [ForeignKey("Department")]
        public int Dept_id { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Task2.Models;

namespace Task2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Task2.Models;

namespace Task2.Controllers
{
    public class InstController : Controller
    {
        ITIEntities context = new ITIEntities();

        public IActionResult Index()
        {
            
            List<Instructor> instructors = context.Instructors.ToList();
            return View("Index" , instructors);
        }
        
        public IActionResult DepartmentV(int Id)
        {
            List<Department> Dept = context.Departments.Where(x => x.Id == Id).ToList();
            return View("DepartmentV", Dept);
        }

        public IActionResult CourseV(int id)
        {
            List<Course> Courses = context.Courses.Where(x => x.Id == id).ToList();
            return View("CourseV", Courses);
        }

        public IActionResult CourseV2(int id)
        {
            List<Course> Courses = context.Courses.Where(x => x.Dept_id == id).ToList();
            return View("CourseV", Courses);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Inst/CourseV.cshtml
@model List<Course>

<style>
    .card {
        box-sizing: border-box;
        width: 290px;
        height: 300px;
        background: rgba(20, 200, 220, 0.58);
        border: 1px solid white;
        box-shadow: 12px 17px 51px rgba(0, 0, 0, 0.22);
        backdrop-filter: blur(6px);
        border-radius: 17px;
        text-align: center;
        cursor: pointer;
        transition: all 0.5s;
        display: inline-block;
        align-items: center;
        justify-content: center;
        user-select: none;
        font-weight: bolder;
        color: black;
        padding:50px;
        margin : 25px;

    }

        .card:hover {
            border: 1px solid black;
            transform: scale(1.05);
        }

        .card:active {
            transform: scale(0.95) rotateZ(1.7deg);
        }
</style>

@foreach(var item in Model)
{
    <div class="card">
        <p> <h3>(@item.Id) @item.Name </h3><br>MinDegree: @item.minDegree<br>Degree: @item.Degree</p>
    </div>

}

Views/Inst/DepartmentV.cshtml
@model List<Department>
<style>
    body{
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: #ECFEFF;
    }


    .flip-card {
        background-color: transparent;
        width: 290px;
        height: 354px;
        perspective: 1000px;
        font-family: sans-serif;
        text-align: center;
        position: absolute;
        top :100px;
        right :570px;
    }

    .title {
        font-size: 1.5em;
        font-weight: 900;
        text-align: center;
        margin: 0;
    }

    .flip-card-inner {
        position: relative;
        width: 100%;
        height: 100%;
        text-align: center;
        transition: transform 0.8s;
        transform-style: preserve-3d;
    }

    .flip-card:hover .flip-card-inner {
        transform: rotateY(180deg);
    }

    .flip-card-front, .flip-card-back {
        box-shadow: 0 8px 14px 0 rgba(0,0,0,0.2);
        position: absolute;
        display: flex;
        flex-direction: column;
        justify-content: center;
        width: 100%;
        height: 100%;
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
        border: 1px solid #0E7490;
        border-radius: 1rem;
    }

    .flip-card-front {
        background: linear-gradient(120deg, #22D3EE 60%, #A5F3FC 88%, rgb(0, 211, 195) 40%, rgb(50, 100, 220, 0.603) 48%);
        color: #164E63;
    }

    .flip-card-back {
        background: linear-gradient(120deg, rgb(50, 100, 220, 0.603) 30%, #A5F3FC 88%, #164E63 40%, #22D3EE 78%);
        color: white;
        transform: rotateY(180deg);
    }

</style>
@foreach(var item in Model)
{

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title">(@item.Id)</p>
                <h2>@item.Name</h2>
            </div>
            <div class="flip-card-back">
                <h4>Department Manger</h4>
                <h1>Dr: @item.Manager</h1>
            </div>
        </div>
    </div>

    <div>
        <a asp-controller="Inst" asp-action="CourseV2" asp-route-id="@item.Id">Show all Courses in The Departmen</a>
    </div>
}

Views/Inst/Index.cshtml
@model List<Instructor>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Image</th>
            <th>Salary</th>
            <th>Address</th>
            <th>Department</th>
            <th>Course</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td><img src="\Images\@item.Image"></td>
                <td>@item.Salary</td>
                <td>@item.Address</td>
                <td><a asp-controller="Inst" asp-action="DepartmentV" asp-route-id="@item.Dept_id">Depatment</a></td>
                <td><a asp-controller="Inst" asp-action="CourseV" asp-route-id="@item.Crs_id">Course</a></td>
            </tr>
        }
    </thead>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Task2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>